### ISSUE TITLE
Finally keyword missing

### ISSUE THREAD

**Issue by halfabench** [YellowAfterlife/HaxMin#4]
Hi!
As mentionned there (http://yal.cc/introducing-haxmin/#comment-344367) output is corrupt when finally keyword is found in javascript input: a semi colon is added after the catch block, the finally keyword is not taken into account.

js input: 
try {}catch(e){} finally{}

js output:
try {} catch(e){}; finally // -> error unexpected token finally

Thanks!

**Comment by YellowAfterlife** [comment]
Fixed in https://github.com/YellowAfterlife/HaxMin/commit/ed2946dee716d73b3baf59d813f97ac150da7656. The keyword was present in keyword list but was not included in checks as I have not previously stumbled upon any test cases that used it, and thus have forgotten to include a check.
