### ISSUE TITLE
void operator in condition statement

### ISSUE THREAD

**Issue by halfabench** [YellowAfterlife/HaxMin#6]
Hi,
another Issue I ran into, is the use of the void operator in a condition statement

For instance: 

if (x === void 0) {
 // XXX
}

because void becomes $void in the output. 

If I read the doc (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void) I think it could be fixed by replacing void 0 by void(0).

:)

**Comment by YellowAfterlife** [comment]
Fixed in https://github.com/YellowAfterlife/HaxMin/commit/829ca5407c8fb79deb37ff7337bb4b8539e68ad9 - no need for void(0), just had to add it to default exclusion list.

**Comment by halfabench** [comment]
ok! Thanks :)
